### ISSUE TITLE
DB schema changes cause crash

### ISSUE THREAD

**Issue by BlueMM75** [AqlaSolutions/FirefoxHistoryMerger#2]
When trying to combine two Places.sqlite, one from around Nov & Firefox 55, and a current one with Firefox 56, I get the following error:

```
D:\>FirefoxHistoryMerger.exe
Opening main file D:\places\current.sqlite
Self check (start): 1426 places without visits and 0 visits with missed places

Opening D:\places\old.sqlite
Self check (input): 1282 places without visits and 0 visits with missed places
Writing 134143 places and 212819 visits from D:\places\old.sqlite

Unhandled Exception: System.Data.SQLite.SQLiteException: SQL logic error or missing database
table moz_places has no column named favicon_id
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FirefoxHistoryMerger.FirefoxHistoryMerger.Insert(SQLiteConnection connection, String table, Dictionary`2 entity, SQLiteCommand& cmd) in d:\My Documents\Aqla\FirefoxHistoryMerger\FirefoxHistoryMerger\FirefoxHistoryMerger.cs:line 29
   at FirefoxHistoryMerger.FirefoxHistoryMerger.<>c__DisplayClass5_0.<CombineHistory>b__4(SQLiteConnection connection) in d:\My Documents\Aqla\FirefoxHistoryMerger\FirefoxHistoryMerger\FirefoxHistoryMerger.cs:line 98
   at FirefoxHistoryMerger.FirefoxHistoryMerger.<>c__DisplayClass8_0.<DoWithDb>b__0(SQLiteConnection c) in d:\My Documents\Aqla\FirefoxHistoryMerger\FirefoxHistoryMerger\FirefoxHistoryMerger.cs:line 171
   at FirefoxHistoryMerger.FirefoxHistoryMerger.DoWithDb[T](String file, Func`2 action) in d:\My Documents\Aqla\FirefoxHistoryMerger\FirefoxHistoryMerger\FirefoxHistoryMerger.cs:line 189
   at FirefoxHistoryMerger.FirefoxHistoryMerger.DoWithDb(String file, Action`1 action) in d:\My Documents\Aqla\FirefoxHistoryMerger\FirefoxHistoryMerger\FirefoxHistoryMerger.cs:line 158
   at FirefoxHistoryMerger.FirefoxHistoryMerger.CombineHistory(String[] placesFiles, String appendToFile, String whereSql) in d:\My Documents\Aqla\FirefoxHistoryMerger\FirefoxHistoryMerger\FirefoxHistoryMerger.cs:line 45
   at FirefoxHistoryMerger.Program.Main(String[] args) in d:\My Documents\Aqla\FirefoxHistoryMerger\FirefoxHistoryMerger\Program.cs:line 16
```

So it looks like it has problems with the Favicon being split out into it's own database.
Any chance of a fix, and new binary release?

**Comment by AqlaSolutions** [comment]
Hah, Firefox reseted my old history again. May be in a month or two I'll come back here and update it.
